default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: activid_development

test:
  <<: *default
  database: activid_test

production:
  <<: *default
  database: activid_production
  password: <%= ENV['ACTIVID_DATABASE_PASSWORD'] %>
