categories:
  - name: Calm
    songs:
      - name: To Ohio (The Low Anthem)
        url: https://s3-us-west-2.amazonaws.com/activid-stagingg/The+Low+Anthem+-+To+Ohio.mp3
  - name: Dramatic
    songs:
      - name: A Voice in Svay Pak (Tony Anderson)
        url: https://s3-us-west-2.amazonaws.com/activid-stagingg/Tony+Anderson-A+Voice+in+Svay+Pak.mp3 
  - name: Energetic
    songs:
      - name: One Afternoon (Scott & Brendo)
        url: https://s3-us-west-2.amazonaws.com/activid-stagingg/Scott+%26+Brendo+-+One+Afternoon.mp3
  - name: Happy
    songs:
      - name: What We Found (Light Club)
        url: https://s3-us-west-2.amazonaws.com/activid-stagingg/Light+Club+-+What+We+Found+(Instrumental).mp3
  - name: Inspirational
    songs:
      - name: Your Heart (Dirty South)
        url: https://s3-us-west-2.amazonaws.com/activid-stagingg/Dirty+South+-+Your+Heart+(feat.+Joe+Gil).mp3
