categories:
  - name: Death Metal
    songs:
      - name: Lack Of Comprehension
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=1
      - name: Crystal Mountain
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=2
      - name: We Will Rise
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=3
      - name: Only For The Weak
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=4
      - name: Angel Of Death
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=5
  - name: Smooth Jazz
    songs:
      - name: Smile
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=6
      - name: Truth B Told
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=7
      - name: Slam Dunk
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=8
      - name: Soul Quest
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=9
      - name: Got 2 Be Groovin'
        url: http://activid-stagingg.s3.amazonaws.com/sorry.mp3?foo=10
